### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by bdmbdsm** [VoldMaire/JuliaPortfolio#1]
А якщо ті, в кого ти пи\*диш, зпи\*дять звідси? Ти подумав про це?

**Comment by VoldMaire** [comment]
я не пи*** я роблю сам)

**Comment by VoldMaire** [comment]
на бакет зараз перейду

**Comment by VoldMaire** [comment]
все одно поки лише шаблон

**Comment by bdmbdsm** [comment]
це я мав іш'ю закривати
